# Generated by Django 3.1.5 on 2021-01-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
